export const FETCHING_TEST_LETTERS = 'FETCHING_TEST_LETTERS'
export const FETCHING_TEST_LETTERS_DONE = 'FETCHING_TEST_LETTERS_DONE'
export const LETTER_PRESSED = 'LETTER_PRESSED'
export const GAME_RESET = 'GAME_RESET'